### ISSUE TITLE
install err

### ISSUE THREAD

**Issue by helgasoft** [Camil88/geoMapX#1]
Trying to install the package, but it fails with following error:
<pre>
/GeoMapX/R/mod_mapAnalysis.R:303:9: unexpected '}'
302:             htmltools::HTML(clearDrawJS)                  
303:         }
             ^
ERROR: unable to collate and parse R files for package 'GeoMapX'
</pre>
Looks like a missing closing parenthesis in _runjs_ call.

**Comment by Camil88** [comment]
I added parenthesis, thanks for your issue. Some time ago I sligthly edited the code just to make it look prettier (removed blank spaces, redundant comments etc.) and most likely I accidentally removed this parenthesis either. If you have any other issues just let me know.

**Comment by helgasoft** [comment]
Thank you, it loads now.

Next problem is 
<pre>
Please supply addMapboxGL() with a Mapbox access token, either via `options(mapbox.accessToken = "...")` or as an argument to `addMapboxGL()`. (If you're not using Mapbox URLs, you can set the access token to `NA`.)
</pre>
If the project is cloned, the user can embed its own Mapbox access token in the source code.
Would be nice however to have a Settings feature so one can do it from inside the app.

**Comment by Camil88** [comment]
That could be an option, thanks for the idea.
